# Generated by Django 5.1.2 on 2024-11-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buzzn', '0003_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='Buzzn/images/'),
        ),
    ]
